name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"] #Waiting for onnxrutime support for 3.14t
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Setup Python
        run: uv python install ${{ matrix.python-version }}

      - name: Pin Python version
        run: uv python pin ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=src --cov-fail-under=100
        env:
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY || 'dummy_key' }}
